### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by cgsdev0** [erikodes-community/fixit#4]
looping over the `people` array is a costly O(n) complexity, where n is ~7.8 billion currently

we should probably look into using b-trees to find the `erik` person more efficiently

**Comment by hastyquickbeam** [comment]
Thank you, good observation.

Do you recommend using a library or coding the b-tree from scratch?

**Comment by hastyquickbeam** [comment]
Alternately, if we use a dict, that would make lookup fast.
